# vector

## interpretation

### algebraic
+ ordered list of numbers
  + 2 dimentional array
  + has 1 length dimention


### geometric
+ encoded arrow
  + magnitude
  + angle

In [2]:
import numpy as np

## orientation
+ row direction - $(1, n)$
+ column direction - $(n, 1)$

In [2]:
a = [1, 2, 3]
array_a = np.array(a)
row_vec_a = np.array([a])
col_vec_a = np.array([a]).T
array_a, row_vec_a, col_vec_a

(array([1, 2, 3]),
 array([[1, 2, 3]]),
 array([[1],
        [2],
        [3]]))

In [3]:
print(f'asList: {np.shape(a)}')
print(f'asArray: {array_a.shape}')
print(f'rowVec: {row_vec_a.shape}')
print(f'colVec: {col_vec_a.shape}')

asList: (3,)
asArray: (3,)
rowVec: (1, 3)
colVec: (3, 1)


## simple operation

### linear combination
+ operate every elements for real number multiplication
+ operate corresponding elements for sumation and subtraction
  + for two same shape vectors

In [8]:
v = np.array([[4,5,6]])
w = np.array([[10,20,30]])
- 1 * v, v + w, v - w, 

(array([[-4, -5, -6]]), array([[14, 25, 36]]), array([[ -6, -15, -24]]))

### transpose
+ change orientation

In [9]:
v.T, v.T.T

(array([[4],
        [5],
        [6]]),
 array([[4, 5, 6]]))

### broadcasting
+ repeating operation based on one vector

In [12]:
10 + w, v + w.T

(array([[20, 30, 40]]),
 array([[14, 15, 16],
        [24, 25, 26],
        [34, 35, 36]]))

## norm
+ magnitude of a vector
$$\lVert v \rVert = \sqrt{\sum_{i=1}^{n}{v_i^2}}$$

In [14]:
v = np.array([1,2,3,7,8,9])
v_dim = len(v) # 수학의 차원
v_mag = np.linalg.norm(v) # 수학적 크기, 길이, 또는 노름
v_dim, v_mag

(6, 14.422205101855956)

In [5]:
v = np.array([1,2,3,7,8,9])
np.sqrt(np.sum(v**2)), np.linalg.norm(v)

(14.422205101855956, 14.422205101855956)

## unit vector
+ vector of magnitude 1
$$\hat{v} = \frac{v}{\lVert v \rVert}$$

In [6]:
v = np.array([1,2,3,7,8,9])

def unit_vector(vector):
    norm = np.linalg.norm(v)
    return v/norm

unit_vector(v)

array([0.06933752, 0.13867505, 0.20801257, 0.48536267, 0.5547002 ,
       0.62403772])

## dot product
+ simmilarity of two vectors
$$\delta = \sum_{i=1}^{n}{a_ib_i} = v^Tw = \lVert v \rVert \lVert w \rVert cos(\theta_{v, w})$$

In [15]:
v = np.array([1,2,3,4])
w = np.array([5,6,7,8])
np.dot(v,w)

70

### distributive law
$$a^T(b+c) = a^Tb+a^Tc$$

In [16]:
a = np.array([ 0,1,2 ])
b = np.array([ 3,5,8 ])
c = np.array([ 13,21,34 ])
# 내적 분배 법칙
res1 = np.dot( a, b+c )
res2 = np.dot( a,b ) + np.dot( a,c )
res1, res2

(110, 110)

## Hardamard product
+ multiply corresponding elements

In [18]:
a = np.array([5,4,8,2])
b = np.array([1,0,.5, -1])
a * b

array([ 5.,  0.,  4., -2.])

## cross product
+ row - row vector scalar multiplied by the corresponding column vector element
+ column - column vector scalar multiplied by the corresponding row vector element
$$v \times w = vw^T$$

In [4]:
a = np.array([5,4,8,2])
b = np.array([1,0,.5, -1])
np.outer(a, b)

array([[ 5. ,  0. ,  2.5, -5. ],
       [ 4. ,  0. ,  2. , -4. ],
       [ 8. ,  0. ,  4. , -8. ],
       [ 2. ,  0. ,  1. , -2. ]])

## orthogonal projection
+ find $\beta$ to project vector **b** to vector **a**
  + projetion vector : $\beta \bold{a}$
  + perpendicular to vector **a** : $\bold{b} - \beta \bold{a}$
$$
\bold{a}^T(\bold{b}-\beta \bold{a}) = 0\\
\bold{a}^T\bold{b} - \beta \bold{a}^T \bold{a} = 0\\
\beta = \frac{\bold{a}^T\bold{b}}{\bold{a}^T\bold{a}}
$$

## orthogonal decomposition
+ decompose vector **t** for basis vector **r** 
$$
\bold{t}_{\parallel \bold{r}} = \bold{r}\frac{\bold{t}^T\bold{r}}{\bold{r}^T\bold{r}}\\
\bold{t}_{\perp \bold{r}}= \bold{t} - \bold{t}_{\parallel \bold{r}} = \bold{t} - \bold{r}\frac{\bold{t}^T\bold{r}}{\bold{r}^T\bold{r}}
$$

# exercise

In [4]:
# 1-4
def mag_vector(lenghth, vector):
    return lenghth / np.linalg.norm(vector) * vector

mag_vector(2, np.array([[1, 1]]))

array([[1.41421356, 1.41421356]])

In [7]:
# 1-5
def transpose(vector):
    row, col = vector.shape
    new_vec = np.zeros((col, row))
    for i in range(row):
        for j in range(col):
            new_vec[j][i] = vector[i][j]
    return new_vec
            

transpose(np.array([[1, 2, 3]]))

array([[1.],
       [2.],
       [3.]])

In [11]:
# 1-6
v = np.array([[1, 2, 3]])
np.linalg.norm(v)**2, v @ v.T 

(14.0, array([[14]]))

In [19]:
# 1-7
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])

a @ b.T, b @ a.T

(array([[32]]), array([[32]]))

In [15]:
# 1-9
def orthogonal_decompose(vector, basis):
    beta = (basis @ vector.T) / (basis @ basis.T)
    perp = vector - beta * basis
    para = beta * basis
    return perp, para

a, b = orthogonal_decompose(np.array([[1, 2, 3]]), np.array([[4, 5, 6]]))
a+b, a @ b.T

(array([[1., 2., 3.]]), array([[-6.66133815e-16]]))

## linear weighted combination
+ same demention for all $\bold{v}_n$
+ real number for all $\lambda_n$
$$\bold{w} = \lambda_1 \bold{v}_1 + \lambda_2 \bold{v}_2 + \dots + \lambda_n \bold{v}_n$$

## linearly dependence
+ for all vector in vector set
+ real number for all $\lambda_n$
+ nontraival solution exisit for equation:
$$\bold{0} = \lambda_1 \bold{v}_1 + \lambda_2 \bold{v}_2 + \dots + \lambda_n \bold{v}_n$$ 

## span
+ for all vectors in vector set
+ apply every possible linear weighted combination
+ form subspace

## basis
+ for all vectors in vector set
  + span subspace
  + linearly independence